//src/app/constants/mockdata.ts
export const testResult = [
  {
    "1. symbol": "MLGO",
    "2. name": "MicroAlgo Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.5556",
  },
  {
    "1. symbol": "MBOT",
    "2. name": "Microbot Medical Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.4444",
  },
  {
    "1. symbol": "MCHP",
    "2. name": "Microchip Technology Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.4444",
  },
  {
    "1. symbol": "CY9D.FRK",
    "2. name": "Microbot Medical Inc",
    "3. type": "Equity",
    "4. region": "Frankfurt",
    "5. marketOpen": "08:00",
    "6. marketClose": "20:00",
    "7. timezone": "UTC+02",
    "8. currency": "EUR",
    "9. matchScore": "0.4000",
  },
  {
    "1. symbol": "MCHPP",
    "2. name": "Microchip Technology Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.4000",
  },
  {
    "1. symbol": "MBX.TRT",
    "2. name": "Microbix Biosystems Inc.",
    "3. type": "Equity",
    "4. region": "Toronto",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-05",
    "8. currency": "CAD",
    "9. matchScore": "0.3636",
  },
  {
    "1. symbol": "MALG",
    "2. name": "Microalliance Group Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.3571",
  },
  {
    "1. symbol": "MBXBF",
    "2. name": "Microbix Biosystems Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.3571",
  },
  {
    "1. symbol": "0K19.LON",
    "2. name": "Microchip Technology Inc.",
    "3. type": "Equity",
    "4. region": "United Kingdom",
    "5. marketOpen": "08:00",
    "6. marketClose": "16:30",
    "7. timezone": "UTC+01",
    "8. currency": "USD",
    "9. matchScore": "0.3333",
  },
  {
    "1. symbol": "VENAF",
    "2. name": "MicroAlgo Inc - Warrants (30/04/2027)",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.2381",
  },
];

export const testFilterOptions = {
  types: ["Equity"],
  regions: ["United States", "Frankfurt", "Toronto", "United Kingdom"],
  currencies: ["USD", "EUR", "CAD"],
};
