//src/app/constants/mockdata.ts
export const testResult = [
  {
    "1. symbol": "MLGO",
    "2. name": "MicroAlgo Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.5556",
  },
  {
    "1. symbol": "MBOT",
    "2. name": "Microbot Medical Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.4444",
  },
  {
    "1. symbol": "MCHP",
    "2. name": "Microchip Technology Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.4444",
  },
  {
    "1. symbol": "CY9D.FRK",
    "2. name": "Microbot Medical Inc",
    "3. type": "Equity",
    "4. region": "Frankfurt",
    "5. marketOpen": "08:00",
    "6. marketClose": "20:00",
    "7. timezone": "UTC+02",
    "8. currency": "EUR",
    "9. matchScore": "0.4000",
  },
  {
    "1. symbol": "MCHPP",
    "2. name": "Microchip Technology Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.4000",
  },
  {
    "1. symbol": "MBX.TRT",
    "2. name": "Microbix Biosystems Inc.",
    "3. type": "Equity",
    "4. region": "Toronto",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-05",
    "8. currency": "CAD",
    "9. matchScore": "0.3636",
  },
  {
    "1. symbol": "MALG",
    "2. name": "Microalliance Group Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.3571",
  },
  {
    "1. symbol": "MBXBF",
    "2. name": "Microbix Biosystems Inc",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.3571",
  },
  {
    "1. symbol": "0K19.LON",
    "2. name": "Microchip Technology Inc.",
    "3. type": "Equity",
    "4. region": "United Kingdom",
    "5. marketOpen": "08:00",
    "6. marketClose": "16:30",
    "7. timezone": "UTC+01",
    "8. currency": "USD",
    "9. matchScore": "0.3333",
  },
  {
    "1. symbol": "VENAF",
    "2. name": "MicroAlgo Inc - Warrants (30/04/2027)",
    "3. type": "Equity",
    "4. region": "United States",
    "5. marketOpen": "09:30",
    "6. marketClose": "16:00",
    "7. timezone": "UTC-04",
    "8. currency": "USD",
    "9. matchScore": "0.2381",
  },
];

export const testFilterOptions = {
  types: ["Equity"],
  regions: ["United States", "Frankfurt", "Toronto", "United Kingdom"],
  currencies: ["USD", "EUR", "CAD"],
};

// Map regions to countries
export const REGION_TO_COUNTRY: { [key: string]: string } = {
  "United States": "United States",
  Frankfurt: "Germany",
  Toronto: "Canada",
  "United Kingdom": "United Kingdom",
  Japan: "Japan",
  "Hong Kong": "China",
  Shanghai: "China",
  Shenzhen: "China",
  Mumbai: "India",
  Singapore: "Singapore",
  Amsterdam: "Netherlands",
  Paris: "France",
  Milan: "Italy",
  Brussels: "Belgium",
  Lisbon: "Portugal",
  Madrid: "Spain",
  Switzerland: "Switzerland",
  Sweden: "Sweden",
  Oslo: "Norway",
  Copenhagen: "Denmark",
  Helsinki: "Finland",
  Vienna: "Austria",
  Seoul: "South Korea",
  Taiwan: "Taiwan",
  Thailand: "Thailand",
  Indonesia: "Indonesia",
  Malaysia: "Malaysia",
  Australia: "Australia",
  "New Zealand": "New Zealand",
  Brazil: "Brazil",
  Mexico: "Mexico",
  Argentina: "Argentina",
  Chile: "Chile",
  Colombia: "Colombia",
  Peru: "Peru",
  "South Africa": "South Africa",
  Israel: "Israel",
  Turkey: "Turkey",
  "Saudi Arabia": "Saudi Arabia",
  UAE: "United Arab Emirates",
  Qatar: "Qatar",
  Russia: "Russia",
};

// Map regions to Bloomberg exchange codes
export const REGION_TO_EXCHANGE_CODE: { [key: string]: string } = {
  "United States": "US",
  Frankfurt: "GR",
  Toronto: "CN",
  "United Kingdom": "LN",
  Japan: "JP",
  "Hong Kong": "HK",
  Shanghai: "CH",
  Shenzhen: "CH",
  Mumbai: "IN",
  Singapore: "SP",
  Amsterdam: "NA",
  Paris: "FP",
  Milan: "IM",
  Brussels: "BB",
  Lisbon: "PL",
  Madrid: "SM",
  Switzerland: "SW",
  Sweden: "SS",
  Oslo: "NO",
  Copenhagen: "DC",
  Helsinki: "FH",
  Vienna: "AV",
  Seoul: "KS",
  Taiwan: "TT",
  Thailand: "TB",
  Indonesia: "IJ",
  Malaysia: "MK",
  Australia: "AU",
  "New Zealand": "NZ",
  Brazil: "BZ",
  Mexico: "MM",
  Argentina: "AR",
  Chile: "CI",
  Colombia: "CB",
  Peru: "PE",
  "South Africa": "SJ",
  Israel: "IT",
  Turkey: "TI",
  "Saudi Arabia": "AB",
  UAE: "UH",
  Qatar: "QD",
  Russia: "RX",
};

// Generate Bloomberg-style ticker
export function generateBloombergTicker(
  symbol: string,
  region: string
): string {
  const exchangeCode = REGION_TO_EXCHANGE_CODE[region] || "UN"; // Default to Unknown

  // For US stocks with .X symbol format, strip the extension for Bloomberg style
  const cleanSymbol = symbol.includes(".") ? symbol.split(".")[0] : symbol;

  return `${cleanSymbol} ${exchangeCode} Equity`;
}

// Get country from region
export function getCountryFromRegion(region: string): string {
  return REGION_TO_COUNTRY[region] || region;
}
